<?php

namespace RB\CoreBundle\Repository;

/**
 * AttrTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttrTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
