<?php

namespace RB\CoreBundle\Repository;

/**
 * AttrValuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttrValuesRepository extends \Doctrine\ORM\EntityRepository
{
}
