<?php

namespace RB\CoreBundle\Repository;

/**
 * AttrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttrRepository extends \Doctrine\ORM\EntityRepository
{
}
