<?php

namespace RB\CoreBundle\Repository;

/**
 * TraceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraceRepository extends \Doctrine\ORM\EntityRepository
{
}
